services:
  - docker

script:
  - ./build.sh
  - ./test.sh

deploy:
  - provider: script
    script: bash push.sh
    on:
#      tags: true
      all_branches: true
  - provider: releases
    api_key: "GITHUB_OAUTH_TOKEN"
    file:
      - "samba/secrets/*"
      - "backup/root/*"
    skip_cleanup: true
    on:
#      tags: true
      all_branches: true
