version: '3'

networks:
  samba:
    external:
      name: 4samba_default

volumes:
  nextcloud:
    external: true
  nextcloudDb:
    external: true

services:

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - nextcloudDb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
##    depends_on:
#      - db-setup
#  db-setup:
#    image: alpine:latest
#    command: >
#      ash -c "apk add docker &&
#              docker volume create nextcloudDb"
    
  app:
    image: "bob5ec/nextcloud:${ENV}"
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /data:/data
      - /data/nextcloud:/var/www/html/data
    networks:
      - default
      - samba
    external_links:
      - samba
    restart: always
    depends_on:
      - db
      - config
  config:
    build: .
    image: "bob5ec/nextcloud:${ENV}"
    volumes:
      - ./5nextcloud/config:/config
      - ./5nextcloud/secrets:/secrets
      - nextcloud:/var/www/html
      - /data:/data
      - /data/nextcloud:/var/www/html/data
    depends_on:
      - db
    entrypoint: ["/bin/bash"]
    command: ["/config/setup"]
