version: '3'

volumes:
  nextcloud:
  nextcloudDb:
    external: true

services:

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - nextcloudDb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
##    depends_on:
#      - db-setup
#  db-setup:
#    image: alpine:latest
#    command: >
#      ash -c "apk add docker &&
#              docker volume create nextcloudDb"
    
  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=coruscant.home.asd.bz coruscant localhost
    volumes:
      - nextcloud:/var/www/html
      - /data:/data
      - /data/nextcloud:/var/www/html/data
    restart: always
    depends_on:
      - db
      - config
  config:
    build: .
    image: nextcloud
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/secrets:/secrets
      - nextcloud:/var/www/html
      - /data:/data
      - /data/nextcloud:/var/www/html/data
    depends_on:
      - db
    entrypoint: ["/bin/bash"]
    command: ["/config/setup"]
