version: "3"

services:
  nfs4:
    image: joebiellik/nfs4

    # Required to load kernel NFS module
    privileged: true

    volumes:
      # You must provide an exports config file
      - /home/lars/admin/running-docker-stack/nfs/exports:/etc/exports

      # Shares
 #     - /data:/data
 #     - /data2:/data2

    ports:
      - "111:111/udp"
      - "2049:2049/tcp"
      - "2049:2049/udp"

#    deploy:
#      placement:
#        constraints: [node.disk == data]
#networks:
#    voteapp:

#volumes:
#  db-data:
