#!/bin/sh
# exit when any command fails
set -e

# create 0.netrc containing login data
COUNT=`cat /secrets/users | jq '.users|length'`
#testing for valid and one invalid user (which is added by one off bug :-)
for i in `seq 0 $COUNT`; do
  user=`cat /secrets/users | jq ".users[$i].name" -r`
  password=`cat /secrets/users | jq ".users[$i].password" -r`
  echo "machine app login $user password $password" > $i.netrc
done
for i in `seq 0 $COUNT`; do
	echo testing user $i
	cp $i.netrc .netrc
	cadaver -r /cadaver.rc
done

#keep the container runing
tail -f /dev/null
