#!/bin/bash
function occ {
	cmd="php /var/www/html/occ $@"
	echo "$cmd"
	su www-data -s /bin/bash -c "$cmd"
}


/config/wait-for-it/wait-for-it.sh db:3306

occ app:enable files_external
id=$(occ files_external:create /data local null::null --output json)
echo $id
#TODO get id
occ files_external:config $id "datadir" "/data"
occ files_external:applicable --add-user lars $id
